### PR TITLE
SDanger: Major update - Blog Posts, Theme, CSS Styling, Bio, Bug fixes

### PR DESCRIPTION
**Pull request by scarlett-danger**
I updated several areas to improve the website. I added a new blog post, updated the grammar in the bio section, fixed the mobile nav bug, updated the theme

### CODE REVIEW

**Comment by aleksa-codes** [comment]
I checked out the PR and your fork, and noticed that you have not changed this line:
https://github.com/aleksa-codes/astro-portfolio/blob/9c6a72911632e8145a3eb408a0f97139560dd488/src/pages/contact.astro#L27

If you do not change the action value, I will keep getting the emails from the form of your site.

Otherwise, very interesting to see my project in different theme, looks nice.

**Comment by aleksa-codes** [comment]
Hi @scarlett-danger, I checked out the PR and your fork, and noticed that you have not changed this line:
https://github.com/aleksa-codes/astro-portfolio/blob/9c6a72911632e8145a3eb408a0f97139560dd488/src/pages/contact.astro#L27

If you do not change the action value, I will keep getting the emails from the form of your site.

Otherwise, very interesting to see my project in different theme, looks nice.

**Comment by aleksa-codes** [comment]
@scarlett-danger to follow up all you have to do is in action put you email:
```
action="https://formsubmit.co/your@email.com"
```
after you send one email via form, you will get a code with which you can replace the email with the code, if u don't want to have email in the code:
```
action="https://formsubmit.co/1234abcd
```

**Comment by aleksa-codes** [comment]
Hi @scarlett-danger I still keep getting emails from your website :)

Maybe you are missing some important emails coming from your contact page, since you still have not changed the action value like I suggested you too. I find it quite strange that you are not replaying to your accident PR and to my comments here. I would expect a comment saying that it was an accident PR or at least a reply to what I commented about the sending of emails, since I also tagged you both times. Hope to hear from you soon.

**Comment by scarlett-danger** [comment]
Hi @aleksa-codes . I am very sorry for the delayed response. I am very busy at work for the holidays and I am just getting to this message now. I can leave a comment on the PR saying it was an accident. Also, I do not have the contact form visible on my website so there shouldn't be any messages being sent to anyone to my knowledge. Have you received any messages? I appreciate you reminding me to update the contact form logic to point to my email from yours.

**Comment by scarlett-danger** [comment]
Note: This is an accidental PR. Please disregard this.

**Comment by aleksa-codes** [comment]
Hello @scarlett-danger, still receiving the mails:
Screenshot 2025-01-22 200759

**Comment by aleksa-codes** [comment]
Hi @scarlett-danger , the GitHub activity is a public information I can see that you had more than enough time to update one value in the code over the last 3 months. I am still receiving the emails from your website. I contacted the GitHub and FormSubmit support team and will resolve it with them. This is a lesson for me to be more careful what I open source and to keep the code for myself more often, since there could be people with "hacker" mindset 🙂 Have a good one.

**Pull request closed without merging**
